### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by mlund** [mlund/coulombgalore#12]
We should define a policy for the units for function arguments and return values. Currently there are suggestions for Hartree units in the comments(?)

ping @bjornstenqvist

**Comment by bjornstenqvist** [comment]
I have at least fixed a temporary solution that I think is OK.

**Comment by bjornstenqvist** [comment]
There are some documentation in README.md. Is that enough or do we need comments also in the code?

**Comment by mlund** [comment]
This seems to be solved
